apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tomcat
spec:
  capacity:
    storage: 7Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hf-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02c910544b268cd36

