
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tomcat
  namespace: tomcat
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: hf-efs-sc
